//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Webpay.Integration.CSharp")]
[assembly: AssemblyDescription("Webpay Integration CSharp")]
[assembly: AssemblyCompany("Svea")]
[assembly: AssemblyProduct("Webpay.Integration.CSharp")]
[assembly: AssemblyVersion("0.0.1")]
[assembly: AssemblyFileVersion("0.0.1")]
[assembly: AssemblyInformationalVersion("0.0.1")]
[assembly: AssemblyCopyright("")]
[assembly: CLSCompliant(true)]

